### ISSUE TITLE
Color Props/State type for React.js

### ISSUE THREAD

**Issue by xavierbriole** [smockle/xcode-default-theme#3]
Hello !

First, thanks for this awesome theme.
The mix with Titlebar-Less is really good.

I would like to know if it's possible to color the type of the Props & States for React.js files :
![Capture d’écran 2019-03-12 à 12 54 59](https://user-images.githubusercontent.com/27001825/54198374-99705500-44c6-11e9-8037-46a585445956.png)
Like this :
![Capture d’écran 2019-03-12 à 12 55 20](https://user-images.githubusercontent.com/27001825/54198387-a2f9bd00-44c6-11e9-8d1b-351530db4264.png)
It would be sooo great!
Thanks and congrats for the work you make :)

**Comment by smockle** [comment]
Hi @xavierbriole, I’m happy you enjoy the theme!

I checked the colors used in Xcode for similar language constructs (e.g. Dictionaries, Tuple Types & Extensions in Swift), and the colors used in `xcode-default-theme` reflect those used in Xcode. I will preserve the existing colors for now.

As an aside—I understand that fidelity to Xcode’s color scheme does not always result in the most usable syntax highlights. In fact, I’ve started using the Xcode Partial variations of this theme personally, because the token scopes are better defined.

Back to your question—if you add this to your `settings.json`, you can customize the key color of TypeScript types used with React (replace `#ff0000` with any other hex color code):
```JSON
"editor.tokenColorCustomizations": {
  "[Xcode Default (Dark)]": {
    "textMateRules": [{
      "scope": "variable.object.property.tsx",
      "settings": {
        "foreground": "#ff0000"
      }
    }]
  }
 },
```

For more information, see [Customizing a Color Theme](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)
